language: go
sudo: false
go:
  - tip
before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
script:
  - go test -v ./decide -coverprofile=profile.cov
  - $HOME/gopath/bin/goveralls -coverprofile=profile.cov -service=travis-ci